version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py --host 0.0.0.0:5000
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - redis
    network_mode: "host"

  redis:
    image: redis:latest



    